export const tags = [
    "animal",
    "dog",
    "forest",
    "camping",
    "outdoors",
    "person",
    "human",
    "nature",
    "canine",
    "plant",
    "pet",
    "grass",
    "apparel",
    "clothing",
    "footwear",
    "english bull terrier",
    "sea",
    "snow",
    "yosemite valley",
    "tree",
    "bulldog",
    "winter",
    "french bulldog",
    "ocean"
]